### PR TITLE
26/3/2019 Chinese version translation final V1.0

### PR DESCRIPTION
**Pull request by EricLiu8539**
26/3/2019 Chinese version translation final V1.0
This page is basically translated, please review. And Let me know if need to revise.
Thank you.

### CODE REVIEW

**Comment by jdubois** [comment]
@jhipstercn I have not advertized yet for "JHipster China", would you like me to do it soon? Is the website ready?

**Comment by jhipstercn** [comment]
Thank you very much for your help! We plan to finish the whole translation in one week, and then use one week to proofread. It is expected to be officially launched on April 15. Please help us to publicize it after completion. Thank you very much.



            
            
                
                    
                            
                                
                            
                            
                                william
                            
                    
                        
                            
                                    邮箱：william@csun.cn
                            
                        
                
            
        


            On 03/26/2019 18:04, Julien Dubois wrote: @jhipstercn I have not advertized yet for "JHipster China", would you like me to do it soon? Is the website ready?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jhipster/cn","title":"jhipster/cn","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jhipster/cn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jdubois in #3: @jhipstercn I have not advertized yet for \"JHipster China\", would you like me to do it soon? Is the website ready?"}],"action":{"name":"View Pull Request","url":"https://github.com/jhipster/cn/pull/3#issuecomment-476554657"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jhipster/cn/pull/3#issuecomment-476554657",
"url": "https://github.com/jhipster/cn/pull/3#issuecomment-476554657",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jdubois** [comment]
Thanks @jhipstercn ! Yes fully agreed on the advertisement, of course! We will also need to do a link (maybe with a Chinese flag? I know some people say the flags are an anti-pattern) from the main English website

**Comment by jhipstercn** [comment]
Sorry for the late reply. I think it's only necessary to have a link to the Chinese version on the homepage. Flags are not necessarily needed. At present, the first edition of translation has been completed, and the translation content will be updated continuously in the future. We will also update the Chinese version synchronously according to the latest content of the main site. Please also help to add links to the Chinese version at the right time. Thank you!



            
            
                
                    
                            
                                
                            
                            
                                william
                            
                    
                        
                            
                                    邮箱：william@csun.cn
                            
                        
                
            
        


            On 04/01/2019 15:37, Julien Dubois wrote: Thanks @jhipstercn ! Yes fully agreed on the advertisement, of course! We will also need to do a link (maybe with a Chinese flag? I know some people say the flags are an anti-pattern) from the main English website

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jhipster/cn","title":"jhipster/cn","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jhipster/cn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jdubois in #3: Thanks @jhipstercn ! Yes fully agreed on the advertisement, of course! We will also need to do a link (maybe with a Chinese flag? I know some people say the flags are an anti-pattern) from the main English website"}],"action":{"name":"View Pull Request","url":"https://github.com/jhipster/cn/pull/3#issuecomment-478469565"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jhipster/cn/pull/3#issuecomment-478469565",
"url": "https://github.com/jhipster/cn/pull/3#issuecomment-478469565",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jdubois** [comment]
Thanks ! I'll check the website and do the link ASAP. I'll also announce it on Twitter, etc...
I just got a new concern: I have no idea how to update our sitemap.xml to take this into account.

**Pull request merged**
